---

- name: reenable cassandra exporter service
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: prometheus-cassandra-exporter

- name: reinit cassandra exporter
  command: initctl reload-configuration

- name: restart cassandra exporter
  service:
    name: prometheus-cassandra-exporter
    state: restarted
